apiVersion: v1
kind: PersistentVolume
metadata:
  name: orders-mongo-pv
spec:
  # empty string means use no StorageClass, we want to bind this pv-pvc
  storageClassName: ""
  capacity:
    # The PVC size must match PV size.
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # it must be /tmp/.*
    # otherwise the delete of the PV will fail when skaffold is terminating.
    path: "/tmp/ticketing/orders"
  claimRef:
    name: orders-mongo-pvc
    namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pvc
spec:
  # empty string means use no StorageClass, we want to bind this pv-pvc
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The PVC size must match PV size.
      storage: 500Mi
