apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pvc
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
