name: deploy-manifests

# when ever we merge a pull request that changed something in infra to master branch (we push to master)
on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

# the ubuntu image comes with docker installed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        # connect to DO cluster
      - run: doctl kubernetes cluster kubeconfig save ticketing
        # apply all files in the infra/k8s folder using namespace
      - run: kubectl apply -f infra/k8s --namespace=ticketing
        # apply all files in the infra/k8s-prod folder using namespace
      - run: kubectl apply -f infra/k8s-prod --namespace=ticketing
        # we need to have these files in their own namespaces, that is not specifying namespace
      - run: kubectl apply -f infra/k8s-prod-no-namespace

