name: tests

on:
  pull_request:

# when ever a pull_request is created, re-opened, updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # take out all code from project
      - uses: actions/checkout@v2
        # run this
      - run: cd auth && npm install && npm run test
